
import * as React from 'react';

const Icons = {
   dashboard:        <i className="fas fa-tachometer-alt"></i>,
   createchar:       <i className="fa fa-heart"></i>,
   soon:             <i className="fa fa-hashtag"></i>,
   missions:         <i className="fa fa-exclamation"></i>,
   covenchat:        <i className="fas fa-comment-dots"></i>,
   profile:          <i className="fa fa-flask"></i>,
   settings:         <i className="fa fa-cog"></i>,
   documentation:    <i className="fa fa-book"></i>,
   apimocking:       <i className="fa fa-bug"></i>,
   coinflipper:      <i className="fas fa-dice"></i>,
   complex:          <i className="fa fa-barcode"></i>,
   plus:             <i className="far fa-plus-square"></i>,
   minus:            <i className="far fa-minus-square"></i>,
   download:         <i className="fas fa-download"></i>,
   calendarPlus:     <i className="fas fa-calendar-plus"></i>,
   calendarMinus:    <i className="fas fa-calendar-minus"></i>,
   calendarTimes:    <i className="fas fa-calendar-times"></i>,
   poweroff:         <i className="fas fa-power-off" />,
   bars:             <i className="fa fa-bars"/>,
   banned:           <i className="fas fa-ban" />,
   lockopen:         <i className="fas fa-lock-open" />,
   trashcan:         <i className="fas fa-trash-alt" />,
   questionmark:     <i className="fas fa-question-circle" />,
   exlamation:       <i className="fas fa-exclamation-triangle"/>,
   file:             <i className="fas fa-file"/>,
   file_image:       <i className="fas fa-file-image"/>,
   file_pdf:         <i className="fas fa-file-pdf"/>,
   file_excel:       <i className="fas fa-file-excel"/>,
   file_powerpoint:  <i className="fas fa-file-powerpoint"/>,
   file_word:        <i className="fas fa-file-word"/>,
   save:             <i className="fas fa-save"/>,
   close:            <i className="fas fa-times" />,
   arrowLeft:        <i className="fas fa-arrow-left" />,
   users:            <i className="fas fa-users" />,
   user:             <i className="fas fa-user" />,
};

export default Icons;
